### ISSUE TITLE
Tests fail because type(float) != np.float32

### ISSUE THREAD

**Issue by chaubold** [ilastik/ilastikrag-fork#2]
```
======================================================================
FAIL: ilastikrag.tests.test_standard_accumulators.TestStandardAccumulators.test_sp_features_with_histogram
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/my/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/path/to/my/lib/python3.6/site-packages/ilastikrag/tests/test_standard_accumulators.py", line 93, in test_sp_features_with_histogram
    assert type(sp_quantiles_25_sum) == np.float32, f"got {type(sp_quantiles_25_sum)} instead of np.float32"
AssertionError: got <class 'float'> instead of np.float32
```

This worked fine 2 months ago. Now I tried to build new packages with @akreshuk's fix, but the tests don't run any more. I suspect that we're getting `pandas` in a newer version that returns other datatypes.

**Comment by k-dominik** [comment]
this seems to be resolved/not an issue anymore.
